export const routes = {
  index: '/',
  dummy: '',
  pageExample: '/page-example',
  login: '/login',
  register: '/register',
  empleados: '/empleados',
  empleado: '/empleado',
  gimnasios: '/gimnasios',
  maquinas: '/maquinas',
  maquina: '/maquina',
  membresias: '/membresias',
  membresia: '/membresia',
  bitacoras: '/bitacoras',
  cursos: '/cursos',
  historialCursos: '/historial-cursos',
};
